FROM python:3.13

WORKDIR /app

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY kafka-producer.py .

# Set the entry point to run the Kafka producer script
ENTRYPOINT ["python", "kafka-producer.py"]
